
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 *
 *
 *  THIS IS A GENERATED FILE.  DO NOT EDIT DIRECTLY
 *  Generated by running:
 *     cd data-references
 *     python3 generate-code-from-data/generate-code-from-data.py
 *
 *
 *!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/

using System.Collections.Generic;

public class WSCountry
{
    public string name;
    public float area_sq_km;
    public ulong population_total;
    public float lattitude = 50f;

    public static List<WSCountry> countries = new List<WSCountry>()
    {
        new WSCountry() {
               name="Afghanistan",
               area_sq_km=652860.0f,
               population_total=37172386,
           },
        new WSCountry() {
               name="Albania",
               area_sq_km=27400.0f,
               population_total=2866376,
           },
        new WSCountry() {
               name="Algeria",
               area_sq_km=2381740.0f,
               population_total=42228429,
           },
        new WSCountry() {
               name="American Samoa",
               area_sq_km=200.0f,
               population_total=55465,
           },
        new WSCountry() {
               name="Andorra",
               area_sq_km=470.0f,
               population_total=77006,
           },
        new WSCountry() {
               name="Angola",
               area_sq_km=1246700.0f,
               population_total=30809762,
           },
        new WSCountry() {
               name="Antigua and Barbuda",
               area_sq_km=440.0f,
               population_total=96286,
           },
        new WSCountry() {
               name="Argentina",
               area_sq_km=2736690.0f,
               population_total=44494502,
           },
        new WSCountry() {
               name="Armenia",
               area_sq_km=28470.0f,
               population_total=2951776,
           },
        new WSCountry() {
               name="Aruba",
               area_sq_km=180.0f,
               population_total=105845,
           },
        new WSCountry() {
               name="Australia",
               area_sq_km=7692020.0f,
               population_total=24992369,
           },
        new WSCountry() {
               name="Austria",
               area_sq_km=82522.998046875f,
               population_total=8847037,
           },
        new WSCountry() {
               name="Azerbaijan",
               area_sq_km=82670.0f,
               population_total=9942334,
           },
        new WSCountry() {
               name="Bahamas, The",
               area_sq_km=10010.0f,
               population_total=385640,
           },
        new WSCountry() {
               name="Bahrain",
               area_sq_km=778.000030517578f,
               population_total=1569439,
           },
        new WSCountry() {
               name="Bangladesh",
               area_sq_km=130170.0f,
               population_total=161356039,
           },
        new WSCountry() {
               name="Barbados",
               area_sq_km=430.0f,
               population_total=286641,
           },
        new WSCountry() {
               name="Belarus",
               area_sq_km=202988.0078125f,
               population_total=9485386,
           },
        new WSCountry() {
               name="Belgium",
               area_sq_km=30280.0f,
               population_total=11422068,
           },
        new WSCountry() {
               name="Belize",
               area_sq_km=22810.0f,
               population_total=383071,
           },
        new WSCountry() {
               name="Benin",
               area_sq_km=112760.0f,
               population_total=11485048,
           },
        new WSCountry() {
               name="Bermuda",
               area_sq_km=54.0000009536743f,
               population_total=63968,
           },
        new WSCountry() {
               name="Bhutan",
               area_sq_km=38143.9990234375f,
               population_total=754394,
           },
        new WSCountry() {
               name="Bolivia",
               area_sq_km=1083300.0f,
               population_total=11353142,
           },
        new WSCountry() {
               name="Bosnia and Herzegovina",
               area_sq_km=51200.0f,
               population_total=3323929,
           },
        new WSCountry() {
               name="Botswana",
               area_sq_km=566730.0f,
               population_total=2254126,
           },
        new WSCountry() {
               name="Brazil",
               area_sq_km=8358140.0f,
               population_total=209469333,
           },
        new WSCountry() {
               name="British Virgin Islands",
               area_sq_km=150.0f,
               population_total=29802,
           },
        new WSCountry() {
               name="Brunei Darussalam",
               area_sq_km=5270.0f,
               population_total=428962,
           },
        new WSCountry() {
               name="Bulgaria",
               area_sq_km=108560.0f,
               population_total=7024216,
           },
        new WSCountry() {
               name="Burkina Faso",
               area_sq_km=273600.0f,
               population_total=19751535,
           },
        new WSCountry() {
               name="Burundi",
               area_sq_km=25680.0f,
               population_total=11175378,
           },
        new WSCountry() {
               name="Cabo Verde",
               area_sq_km=4030.0f,
               population_total=543767,
           },
        new WSCountry() {
               name="Cambodia",
               area_sq_km=176520.0f,
               population_total=16249798,
           },
        new WSCountry() {
               name="Cameroon",
               area_sq_km=472710.0f,
               population_total=25216237,
           },
        new WSCountry() {
               name="Canada",
               area_sq_km=9093510.0f,
               population_total=37058856,
           },
        new WSCountry() {
               name="Cayman Islands",
               area_sq_km=240.0f,
               population_total=64174,
           },
        new WSCountry() {
               name="Central African Republic",
               area_sq_km=622980.0f,
               population_total=4666377,
           },
        new WSCountry() {
               name="Chad",
               area_sq_km=1259200.0f,
               population_total=15477751,
           },
        new WSCountry() {
               name="Channel Islands",
               area_sq_km=197.999992370605f,
               population_total=170499,
           },
        new WSCountry() {
               name="Chile",
               area_sq_km=743532.03125f,
               population_total=18729160,
           },
        new WSCountry() {
               name="China",
               area_sq_km=9388210.0f,
               population_total=1392730000,
           },
        new WSCountry() {
               name="Colombia",
               area_sq_km=1109500.0f,
               population_total=49648685,
           },
        new WSCountry() {
               name="Comoros",
               area_sq_km=1861.00006103516f,
               population_total=832322,
           },
        new WSCountry() {
               name="Congo, Dem. Rep.",
               area_sq_km=2267050.0f,
               population_total=84068091,
           },
        new WSCountry() {
               name="Congo, Rep.",
               area_sq_km=341500.0f,
               population_total=5244363,
           },
        new WSCountry() {
               name="Costa Rica",
               area_sq_km=51060.0f,
               population_total=4999441,
           },
        new WSCountry() {
               name="Cote d'Ivoire",
               area_sq_km=318000.0f,
               population_total=25069229,
           },
        new WSCountry() {
               name="Croatia",
               area_sq_km=55960.0f,
               population_total=4089400,
           },
        new WSCountry() {
               name="Cuba",
               area_sq_km=104020.0f,
               population_total=11338138,
           },
        new WSCountry() {
               name="Curacao",
               area_sq_km=444.0f,
               population_total=159849,
           },
        new WSCountry() {
               name="Cyprus",
               area_sq_km=9240.0f,
               population_total=1189265,
           },
        new WSCountry() {
               name="Czech Republic",
               area_sq_km=77220.0f,
               population_total=10625695,
           },
        new WSCountry() {
               name="Denmark",
               area_sq_km=41990.0f,
               population_total=5797446,
           },
        new WSCountry() {
               name="Djibouti",
               area_sq_km=23180.0f,
               population_total=958920,
           },
        new WSCountry() {
               name="Dominica",
               area_sq_km=750.0f,
               population_total=71625,
           },
        new WSCountry() {
               name="Dominican Republic",
               area_sq_km=48310.0f,
               population_total=10627165,
           },
        new WSCountry() {
               name="Ecuador",
               area_sq_km=248360.0f,
               population_total=17084357,
           },
        new WSCountry() {
               name="Egypt, Arab Rep.",
               area_sq_km=995450.0f,
               population_total=98423595,
           },
        new WSCountry() {
               name="El Salvador",
               area_sq_km=20720.0f,
               population_total=6420744,
           },
        new WSCountry() {
               name="Equatorial Guinea",
               area_sq_km=28050.0f,
               population_total=1308974,
           },
        new WSCountry() {
               name="Eritrea",
               area_sq_km=101000.0f,
               population_total=3213972,
           },
        new WSCountry() {
               name="Estonia",
               area_sq_km=43470.0f,
               population_total=1320884,
           },
        new WSCountry() {
               name="Eswatini",
               area_sq_km=17200.0f,
               population_total=1136191,
           },
        new WSCountry() {
               name="Ethiopia",
               area_sq_km=1000000.0f,
               population_total=109224559,
           },
        new WSCountry() {
               name="Faroe Islands",
               area_sq_km=1396.00006103516f,
               population_total=48497,
           },
        new WSCountry() {
               name="Fiji",
               area_sq_km=18270.0f,
               population_total=883483,
           },
        new WSCountry() {
               name="Finland",
               area_sq_km=303910.0f,
               population_total=5518050,
           },
        new WSCountry() {
               name="France",
               area_sq_km=547556.9921875f,
               population_total=66987244,
           },
        new WSCountry() {
               name="French Polynesia",
               area_sq_km=3660.0f,
               population_total=277679,
           },
        new WSCountry() {
               name="Gabon",
               area_sq_km=257670.0f,
               population_total=2119275,
           },
        new WSCountry() {
               name="Gambia, The",
               area_sq_km=10120.0f,
               population_total=2280102,
           },
        new WSCountry() {
               name="Georgia",
               area_sq_km=69490.0f,
               population_total=3731000,
           },
        new WSCountry() {
               name="Germany",
               area_sq_km=349360.0f,
               population_total=82927922,
           },
        new WSCountry() {
               name="Ghana",
               area_sq_km=227540.0f,
               population_total=29767108,
           },
        new WSCountry() {
               name="Gibraltar",
               area_sq_km=10.0f,
               population_total=33718,
           },
        new WSCountry() {
               name="Greece",
               area_sq_km=128900.0f,
               population_total=10727668,
           },
        new WSCountry() {
               name="Greenland",
               area_sq_km=410450.0f,
               population_total=56025,
           },
        new WSCountry() {
               name="Grenada",
               area_sq_km=340.0f,
               population_total=111454,
           },
        new WSCountry() {
               name="Guam",
               area_sq_km=540.0f,
               population_total=165768,
           },
        new WSCountry() {
               name="Guatemala",
               area_sq_km=107160.0f,
               population_total=17247807,
           },
        new WSCountry() {
               name="Guinea",
               area_sq_km=245720.0f,
               population_total=12414318,
           },
        new WSCountry() {
               name="Guinea-Bissau",
               area_sq_km=28120.0f,
               population_total=1874309,
           },
        new WSCountry() {
               name="Guyana",
               area_sq_km=196850.0f,
               population_total=779004,
           },
        new WSCountry() {
               name="Haiti",
               area_sq_km=27560.0f,
               population_total=11123176,
           },
        new WSCountry() {
               name="Honduras",
               area_sq_km=111890.0f,
               population_total=9587522,
           },
        new WSCountry() {
               name="Hong Kong SAR, China",
               area_sq_km=1050.0f,
               population_total=7451000,
           },
        new WSCountry() {
               name="Hungary",
               area_sq_km=90530.0f,
               population_total=9768785,
           },
        new WSCountry() {
               name="Iceland",
               area_sq_km=100250.0f,
               population_total=353574,
           },
        new WSCountry() {
               name="India",
               area_sq_km=2973190.0f,
               population_total=1352617328,
           },
        new WSCountry() {
               name="Indonesia",
               area_sq_km=1811570.0f,
               population_total=267663435,
           },
        new WSCountry() {
               name="Iran, Islamic Rep.",
               area_sq_km=1628760.0f,
               population_total=81800269,
           },
        new WSCountry() {
               name="Iraq",
               area_sq_km=434128.0078125f,
               population_total=38433600,
           },
        new WSCountry() {
               name="Ireland",
               area_sq_km=68890.0f,
               population_total=4853506,
           },
        new WSCountry() {
               name="Isle of Man",
               area_sq_km=570.0f,
               population_total=84077,
           },
        new WSCountry() {
               name="Israel",
               area_sq_km=21640.0f,
               population_total=8883800,
           },
        new WSCountry() {
               name="Italy",
               area_sq_km=294140.0f,
               population_total=60431283,
           },
        new WSCountry() {
               name="Jamaica",
               area_sq_km=10830.0f,
               population_total=2934855,
           },
        new WSCountry() {
               name="Japan",
               area_sq_km=364560.0f,
               population_total=126529100,
           },
        new WSCountry() {
               name="Jordan",
               area_sq_km=88780.0f,
               population_total=9956011,
           },
        new WSCountry() {
               name="Kazakhstan",
               area_sq_km=2699700.0f,
               population_total=18276499,
           },
        new WSCountry() {
               name="Kenya",
               area_sq_km=569140.0f,
               population_total=51393010,
           },
        new WSCountry() {
               name="Kiribati",
               area_sq_km=810.0f,
               population_total=115847,
           },
        new WSCountry() {
               name="Korea, Dem. People’s Rep.",
               area_sq_km=120410.0f,
               population_total=25549819,
           },
        new WSCountry() {
               name="Korea, Rep.",
               area_sq_km=97489.00390625f,
               population_total=51635256,
           },
        new WSCountry() {
               name="Kosovo",
               area_sq_km=10887.0f,
               population_total=1845300,
           },
        new WSCountry() {
               name="Kuwait",
               area_sq_km=17820.0f,
               population_total=4137309,
           },
        new WSCountry() {
               name="Kyrgyz Republic",
               area_sq_km=191800.0f,
               population_total=6315800,
           },
        new WSCountry() {
               name="Lao PDR",
               area_sq_km=230800.0f,
               population_total=7061507,
           },
        new WSCountry() {
               name="Latvia",
               area_sq_km=62180.0f,
               population_total=1926542,
           },
        new WSCountry() {
               name="Lebanon",
               area_sq_km=10230.0f,
               population_total=6848925,
           },
        new WSCountry() {
               name="Lesotho",
               area_sq_km=30360.0f,
               population_total=2108132,
           },
        new WSCountry() {
               name="Liberia",
               area_sq_km=96320.0f,
               population_total=4818977,
           },
        new WSCountry() {
               name="Libya",
               area_sq_km=1759540.0f,
               population_total=6678567,
           },
        new WSCountry() {
               name="Liechtenstein",
               area_sq_km=160.0f,
               population_total=37910,
           },
        new WSCountry() {
               name="Lithuania",
               area_sq_km=62642.001953125f,
               population_total=2789533,
           },
        new WSCountry() {
               name="Luxembourg",
               area_sq_km=2430.0f,
               population_total=607728,
           },
        new WSCountry() {
               name="Macao SAR, China",
               area_sq_km=30.3999996185303f,
               population_total=631636,
           },
        new WSCountry() {
               name="Madagascar",
               area_sq_km=581800.0f,
               population_total=26262368,
           },
        new WSCountry() {
               name="Malawi",
               area_sq_km=94280.0f,
               population_total=18143315,
           },
        new WSCountry() {
               name="Malaysia",
               area_sq_km=328550.0f,
               population_total=31528585,
           },
        new WSCountry() {
               name="Maldives",
               area_sq_km=300.0f,
               population_total=515696,
           },
        new WSCountry() {
               name="Mali",
               area_sq_km=1220190.0f,
               population_total=19077690,
           },
        new WSCountry() {
               name="Malta",
               area_sq_km=320.0f,
               population_total=483530,
           },
        new WSCountry() {
               name="Marshall Islands",
               area_sq_km=180.0f,
               population_total=58413,
           },
        new WSCountry() {
               name="Mauritania",
               area_sq_km=1030700.0f,
               population_total=4403319,
           },
        new WSCountry() {
               name="Mauritius",
               area_sq_km=2030.0f,
               population_total=1265303,
           },
        new WSCountry() {
               name="Mexico",
               area_sq_km=1943950.0f,
               population_total=126190788,
           },
        new WSCountry() {
               name="Micronesia, Fed. Sts.",
               area_sq_km=700.0f,
               population_total=112640,
           },
        new WSCountry() {
               name="Moldova",
               area_sq_km=32890.0f,
               population_total=3545883,
           },
        new WSCountry() {
               name="Monaco",
               area_sq_km=2.0f,
               population_total=38682,
           },
        new WSCountry() {
               name="Mongolia",
               area_sq_km=1553560.0f,
               population_total=3170208,
           },
        new WSCountry() {
               name="Montenegro",
               area_sq_km=13450.0f,
               population_total=622345,
           },
        new WSCountry() {
               name="Morocco",
               area_sq_km=446300.0f,
               population_total=36029138,
           },
        new WSCountry() {
               name="Mozambique",
               area_sq_km=786380.0f,
               population_total=29495962,
           },
        new WSCountry() {
               name="Myanmar",
               area_sq_km=653080.0f,
               population_total=53708395,
           },
        new WSCountry() {
               name="Namibia",
               area_sq_km=823290.0f,
               population_total=2448255,
           },
        new WSCountry() {
               name="Nauru",
               area_sq_km=20.0f,
               population_total=12704,
           },
        new WSCountry() {
               name="Nepal",
               area_sq_km=143350.0f,
               population_total=28087871,
           },
        new WSCountry() {
               name="Netherlands",
               area_sq_km=33690.0f,
               population_total=17231017,
           },
        new WSCountry() {
               name="New Caledonia",
               area_sq_km=18280.0f,
               population_total=284060,
           },
        new WSCountry() {
               name="New Zealand",
               area_sq_km=263310.0f,
               population_total=4885500,
           },
        new WSCountry() {
               name="Nicaragua",
               area_sq_km=120340.0f,
               population_total=6465513,
           },
        new WSCountry() {
               name="Niger",
               area_sq_km=1266700.0f,
               population_total=22442948,
           },
        new WSCountry() {
               name="Nigeria",
               area_sq_km=910770.0f,
               population_total=195874740,
           },
        new WSCountry() {
               name="North Macedonia",
               area_sq_km=25220.0f,
               population_total=2082958,
           },
        new WSCountry() {
               name="Northern Mariana Islands",
               area_sq_km=460.0f,
               population_total=56882,
           },
        new WSCountry() {
               name="Norway",
               area_sq_km=365123.0078125f,
               population_total=5314336,
           },
        new WSCountry() {
               name="Oman",
               area_sq_km=309500.0f,
               population_total=4829483,
           },
        new WSCountry() {
               name="Pakistan",
               area_sq_km=770880.0f,
               population_total=212215030,
           },
        new WSCountry() {
               name="Palau",
               area_sq_km=460.0f,
               population_total=17907,
           },
        new WSCountry() {
               name="Panama",
               area_sq_km=74340.0f,
               population_total=4176873,
           },
        new WSCountry() {
               name="Papua New Guinea",
               area_sq_km=452860.0f,
               population_total=8606316,
           },
        new WSCountry() {
               name="Paraguay",
               area_sq_km=397300.0f,
               population_total=6956071,
           },
        new WSCountry() {
               name="Peru",
               area_sq_km=1280000.0f,
               population_total=31989256,
           },
        new WSCountry() {
               name="Philippines",
               area_sq_km=298170.0f,
               population_total=106651922,
           },
        new WSCountry() {
               name="Poland",
               area_sq_km=306190.0f,
               population_total=37978548,
           },
        new WSCountry() {
               name="Portugal",
               area_sq_km=91605.595703125f,
               population_total=10281762,
           },
        new WSCountry() {
               name="Puerto Rico",
               area_sq_km=8870.0f,
               population_total=3195153,
           },
        new WSCountry() {
               name="Qatar",
               area_sq_km=11610.0f,
               population_total=2781677,
           },
        new WSCountry() {
               name="Romania",
               area_sq_km=230080.0f,
               population_total=19473936,
           },
        new WSCountry() {
               name="Russian Federation",
               area_sq_km=16376870.0f,
               population_total=144478050,
           },
        new WSCountry() {
               name="Rwanda",
               area_sq_km=24670.0f,
               population_total=12301939,
           },
        new WSCountry() {
               name="Samoa",
               area_sq_km=2830.0f,
               population_total=196130,
           },
        new WSCountry() {
               name="San Marino",
               area_sq_km=60.0f,
               population_total=33785,
           },
        new WSCountry() {
               name="Sao Tome and Principe",
               area_sq_km=960.0f,
               population_total=211028,
           },
        new WSCountry() {
               name="Saudi Arabia",
               area_sq_km=2149690.0f,
               population_total=33699947,
           },
        new WSCountry() {
               name="Senegal",
               area_sq_km=192530.0f,
               population_total=15854360,
           },
        new WSCountry() {
               name="Serbia",
               area_sq_km=87460.0f,
               population_total=6982084,
           },
        new WSCountry() {
               name="Seychelles",
               area_sq_km=460.0f,
               population_total=96762,
           },
        new WSCountry() {
               name="Sierra Leone",
               area_sq_km=72180.0f,
               population_total=7650154,
           },
        new WSCountry() {
               name="Singapore",
               area_sq_km=709.000015258789f,
               population_total=5638676,
           },
        new WSCountry() {
               name="Sint Maarten (Dutch part)",
               area_sq_km=34.0f,
               population_total=40654,
           },
        new WSCountry() {
               name="Slovak Republic",
               area_sq_km=48080.0f,
               population_total=5447011,
           },
        new WSCountry() {
               name="Slovenia",
               area_sq_km=20141.9995117188f,
               population_total=2067372,
           },
        new WSCountry() {
               name="Solomon Islands",
               area_sq_km=27990.0f,
               population_total=652858,
           },
        new WSCountry() {
               name="Somalia",
               area_sq_km=627340.0f,
               population_total=15008154,
           },
        new WSCountry() {
               name="South Africa",
               area_sq_km=1213090.0f,
               population_total=57779622,
           },
        new WSCountry() {
               name="South Sudan",
               area_sq_km=0f,
               population_total=10975920,
           },
        new WSCountry() {
               name="Spain",
               area_sq_km=499563.984375f,
               population_total=46723749,
           },
        new WSCountry() {
               name="Sri Lanka",
               area_sq_km=62710.0f,
               population_total=21670000,
           },
        new WSCountry() {
               name="St. Kitts and Nevis",
               area_sq_km=260.0f,
               population_total=52441,
           },
        new WSCountry() {
               name="St. Lucia",
               area_sq_km=610.0f,
               population_total=181889,
           },
        new WSCountry() {
               name="St. Martin (French part)",
               area_sq_km=54.4f,
               population_total=37264,
           },
        new WSCountry() {
               name="St. Vincent and the Grenadines",
               area_sq_km=390.0f,
               population_total=110210,
           },
        new WSCountry() {
               name="Sudan",
               area_sq_km=0f,
               population_total=41801533,
           },
        new WSCountry() {
               name="Suriname",
               area_sq_km=156000.0f,
               population_total=575991,
           },
        new WSCountry() {
               name="Sweden",
               area_sq_km=407310.0f,
               population_total=10183175,
           },
        new WSCountry() {
               name="Switzerland",
               area_sq_km=39516.0009765625f,
               population_total=8516543,
           },
        new WSCountry() {
               name="Syrian Arab Republic",
               area_sq_km=183630.0f,
               population_total=16906283,
           },
        new WSCountry() {
               name="Tajikistan",
               area_sq_km=138790.0f,
               population_total=9100837,
           },
        new WSCountry() {
               name="Tanzania",
               area_sq_km=885800.0f,
               population_total=56318348,
           },
        new WSCountry() {
               name="Thailand",
               area_sq_km=510890.0f,
               population_total=69428524,
           },
        new WSCountry() {
               name="Timor-Leste",
               area_sq_km=14870.0f,
               population_total=1267972,
           },
        new WSCountry() {
               name="Togo",
               area_sq_km=54390.0f,
               population_total=7889094,
           },
        new WSCountry() {
               name="Tonga",
               area_sq_km=720.0f,
               population_total=103197,
           },
        new WSCountry() {
               name="Trinidad and Tobago",
               area_sq_km=5130.0f,
               population_total=1389858,
           },
        new WSCountry() {
               name="Tunisia",
               area_sq_km=155360.0f,
               population_total=11565204,
           },
        new WSCountry() {
               name="Turkey",
               area_sq_km=769630.0f,
               population_total=82319724,
           },
        new WSCountry() {
               name="Turkmenistan",
               area_sq_km=469930.0f,
               population_total=5850908,
           },
        new WSCountry() {
               name="Turks and Caicos Islands",
               area_sq_km=950.0f,
               population_total=37665,
           },
        new WSCountry() {
               name="Tuvalu",
               area_sq_km=30.0f,
               population_total=11508,
           },
        new WSCountry() {
               name="Uganda",
               area_sq_km=200520.0f,
               population_total=42723139,
           },
        new WSCountry() {
               name="Ukraine",
               area_sq_km=579290.0f,
               population_total=44622516,
           },
        new WSCountry() {
               name="United Arab Emirates",
               area_sq_km=71020.0f,
               population_total=9630959,
           },
        new WSCountry() {
               name="United Kingdom",
               area_sq_km=241930.0f,
               population_total=66488991,
           },
        new WSCountry() {
               name="United States",
               area_sq_km=9147420.0f,
               population_total=327167434,
           },
        new WSCountry() {
               name="Uruguay",
               area_sq_km=175020.0f,
               population_total=3449299,
           },
        new WSCountry() {
               name="Uzbekistan",
               area_sq_km=425400.0f,
               population_total=32955400,
           },
        new WSCountry() {
               name="Vanuatu",
               area_sq_km=12190.0f,
               population_total=292680,
           },
        new WSCountry() {
               name="Venezuela, RB",
               area_sq_km=882050.0f,
               population_total=28870195,
           },
        new WSCountry() {
               name="Vietnam",
               area_sq_km=310070.0f,
               population_total=95540395,
           },
        new WSCountry() {
               name="Virgin Islands (U.S.)",
               area_sq_km=350.0f,
               population_total=106977,
           },
        new WSCountry() {
               name="West Bank and Gaza",
               area_sq_km=6020.0f,
               population_total=4569087,
           },
        new WSCountry() {
               name="Yemen, Rep.",
               area_sq_km=527970.0f,
               population_total=28498687,
           },
        new WSCountry() {
               name="Zambia",
               area_sq_km=743390.0f,
               population_total=17351822,
           },
        new WSCountry() {
               name="Zimbabwe",
               area_sq_km=386850.0f,
               population_total=14439018,
           },
        new WSCountry() {
               name="Arab World",
               area_sq_km=11232647.0079041f,
               population_total=419790588,
           },
        new WSCountry() {
               name="Caribbean small states",
               area_sq_km=404850.0f,
               population_total=7358965,
           },
        new WSCountry() {
               name="Central Europe and the Baltics",
               area_sq_km=1105054.00146484f,
               population_total=102511922,
           },
        new WSCountry() {
               name="Early-demographic dividend",
               area_sq_km=33107751.999054f,
               population_total=3249140605,
           },
        new WSCountry() {
               name="East Asia & Pacific",
               area_sq_km=24396748.4039211f,
               population_total=2328220870,
           },
        new WSCountry() {
               name="East Asia & Pacific (excluding high income)",
               area_sq_km=15913500.0f,
               population_total=2081651801,
           },
        new WSCountry() {
               name="East Asia & Pacific (IDA & IBRD countries)",
               area_sq_km=15793350.0f,
               population_total=2056064424,
           },
        new WSCountry() {
               name="Euro area",
               area_sq_km=2678923.57177734f,
               population_total=341783171,
           },
        new WSCountry() {
               name="Europe & Central Asia",
               area_sq_km=27429224.5884323f,
               population_total=918793590,
           },
        new WSCountry() {
               name="Europe & Central Asia (excluding high income)",
               area_sq_km=22611288.0078125f,
               population_total=417797257,
           },
        new WSCountry() {
               name="Europe & Central Asia (IDA & IBRD countries)",
               area_sq_km=22973438.0078125f,
               population_total=459865205,
           },
        new WSCountry() {
               name="European Union",
               area_sq_km=4238693.57177734f,
               population_total=513213363,
           },
        new WSCountry() {
               name="Fragile and conflict affected situations",
               area_sq_km=12922619.0078735f,
               population_total=515215936,
           },
        new WSCountry() {
               name="Heavily indebted poor countries (HIPC)",
               area_sq_km=17378791.000061f,
               population_total=780234406,
           },
        new WSCountry() {
               name="High income",
               area_sq_km=35144909.0158224f,
               population_total=1210312147,
           },
        new WSCountry() {
               name="IBRD only",
               area_sq_km=69378808.046875f,
               population_total=4772284113,
           },
        new WSCountry() {
               name="IDA & IBRD total",
               area_sq_km=93329453.0459595f,
               population_total=6412522234,
           },
        new WSCountry() {
               name="IDA blend",
               area_sq_km=5955820.0f,
               population_total=555830605,
           },
        new WSCountry() {
               name="IDA only",
               area_sq_km=17994824.9990845f,
               population_total=1084407516,
           },
        new WSCountry() {
               name="IDA total",
               area_sq_km=23950644.9990845f,
               population_total=1640238121,
           },
        new WSCountry() {
               name="Late-demographic dividend",
               area_sq_km=44519022.03125f,
               population_total=2288665963,
           },
        new WSCountry() {
               name="Latin America & Caribbean",
               area_sq_km=20038832.03125f,
               population_total=641357515,
           },
        new WSCountry() {
               name="Latin America & Caribbean (excluding high income)",
               area_sq_km=19018930.0f,
               population_total=609013934,
           },
        new WSCountry() {
               name="Latin America & the Caribbean (IDA & IBRD countries)",
               area_sq_km=19913632.03125f,
               population_total=625569713,
           },
        new WSCountry() {
               name="Least developed countries: UN classification",
               area_sq_km=17762824.9990845f,
               population_total=1009662578,
           },
        new WSCountry() {
               name="Low & middle income",
               area_sq_km=92198311.0147095f,
               population_total=6383958209,
           },
        new WSCountry() {
               name="Low income",
               area_sq_km=13651370.0f,
               population_total=705417321,
           },
        new WSCountry() {
               name="Lower middle income",
               area_sq_km=20141754.9990845f,
               population_total=3022905169,
           },
        new WSCountry() {
               name="Middle East & North Africa",
               area_sq_km=11223466.007843f,
               population_total=448912859,
           },
        new WSCountry() {
               name="Middle East & North Africa (excluding high income)",
               area_sq_km=8641088.0078125f,
               population_total=382896715,
           },
        new WSCountry() {
               name="Middle East & North Africa (IDA & IBRD countries)",
               area_sq_km=8635068.0078125f,
               population_total=378327628,
           },
        new WSCountry() {
               name="Middle income",
               area_sq_km=78546941.0147095f,
               population_total=5678540888,
           },
        new WSCountry() {
               name="North America",
               area_sq_km=18240984.000001f,
               population_total=364290258,
           },
        new WSCountry() {
               name="Not classified",
               area_sq_km=0f,
               population_total=0,
           },
        new WSCountry() {
               name="OECD members",
               area_sq_km=34476483.6157227f,
               population_total=1303529456,
           },
        new WSCountry() {
               name="Other small states",
               area_sq_km=2031822.99911499f,
               population_total=30758989,
           },
        new WSCountry() {
               name="Pacific island small states",
               area_sq_km=64200.0f,
               population_total=2457367,
           },
        new WSCountry() {
               name="Post-demographic dividend",
               area_sq_km=31473668.9923f,
               population_total=1109997273,
           },
        new WSCountry() {
               name="Pre-demographic dividend",
               area_sq_km=17789339.0078735f,
               population_total=919485393,
           },
        new WSCountry() {
               name="Small states",
               area_sq_km=2500872.99911499f,
               population_total=40575321,
           },
        new WSCountry() {
               name="South Asia",
               area_sq_km=4771603.99902344f,
               population_total=1814388744,
           },
        new WSCountry() {
               name="South Asia (IDA & IBRD)",
               area_sq_km=4771603.99902344f,
               population_total=1814388744,
           },
        new WSCountry() {
               name="Sub-Saharan Africa",
               area_sq_km=21242361.000061f,
               population_total=1078306520,
           },
        new WSCountry() {
               name="Sub-Saharan Africa (excluding high income)",
               area_sq_km=21241901.000061f,
               population_total=1078209758,
           },
        new WSCountry() {
               name="Sub-Saharan Africa (IDA & IBRD countries)",
               area_sq_km=21242361.000061f,
               population_total=1078306520,
           },
        new WSCountry() {
               name="Upper middle income",
               area_sq_km=58405186.015625f,
               population_total=2655635719,
           },
        new WSCountry() {
               name="World",
               area_sq_km=127343220.030532f,
               population_total=7594270356,
           },

    };
}
